version: "3.7"
services:
  zipkin-collector:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"
    networks:
      - example
  
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - example

  # Datadog Agent
  # https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=docker
  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=${DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT}
    ports:
      - "8125:8125"
      - "8126:8126"
      - "4317:4317"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    networks:
      - example

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib
  #   command: ["--config=/etc/otel-collector-config.yml"]
  #   volumes:
  #     - ./datadog_otel_collector.yml:/etc/otel-collector-config.yml
  #   ports:
  #     - "4317:4317"
  #   networks:
  #     - example

networks:
  example: